name: Deploy to netcup

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Hier ggf. noch deine Build-Schritte (z.B. npm install, npm run build, etc.)

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp # Ändere dies zu 'ftp', wenn SFTP nicht unterstützt wird
          local-dir: /httpdocs/  # Ordner in deinem Repo, der tatsächlich hochgeladen werden soll
          server-dir: /httpdocs/  # Verzeichnis auf deinem Webspace (ggf. anpassen)
          timeout: 60000 # Timeout auf 60 Sekunden erhöhen
